### ISSUE TITLE
Создать readme.md

### ISSUE THREAD

**Issue by VadimCpp** [bitia-ru/gekkon-frontend#190]
Прошу создать Readme.md и написать инструкцию, как разворачивать проект и как вести разработку

**Comment by levenkov** [comment]
Для какой цели вам это нужно? Вы вообще представляете, что это за проект?

**Comment by VadimCpp** [comment]
> Для какой цели вам это нужно? Вы вообще представляете, что это за проект?

Для какой цели вам это нужно? Хочу развернуть на локальном компе.
Вы вообще представляете, что это за проект? Да, хочу ознакомится с кодом и поучаствовать
