### ISSUE TITLE
Выделять стрелочки разметки, которые отвечают за кадрирование

### ISSUE THREAD

**Issue by SvetlanaBatova** [bitia-ru/gekkon-frontend#309]
Продуктовый тикет: bitia-ru/gekkon#85

**Comment by levenkov** [comment]
Использованные тобой указатели не подходят. Замени, пожалуйста на эти. Можешь их доработать, они не очень аккуратно сделаны.

Важно:

1. Формат предпочтительно использовать SVG, но скорее всего это не получится, т.к. нам очень нужно, чтобы кончик стрелочки в точности совпадал с координатой для маркера. Т.е. кликаем на фотке трассы и точно (с точностью +/- 2 пикселя) должен быть кончик появившегося маркера. Это очень важно при внесении, иначе действий по расстановке стрелочек становится во много раз больше.

2. Визуальный размер стрелочек должен сохраниться с текущим.

3. При отображении стрелочек на фотке трассы надо тоже отображать обновленные стрелочки для единообразия. Не проверял, так ли сейчас сделано.

[pointers.zip](https://github.com/bitia-ru/gekkon-frontend/files/6069083/pointers.zip)
